### ISSUE TITLE
Decommision tea in favour of ::stdlib

### ISSUE THREAD

**Issue by roidelapluie** [voxpupuli/puppet-tea#19]
We should not keep this module around if stdlib accepts new types. This is redundant.

**Comment by roidelapluie** [comment]
Also:

stdlib has WAAaAY more visibility than this module. In addition to that, this module does not have an explicite name.

![tea_set](https://cloud.githubusercontent.com/assets/291750/19309502/7c916c28-9085-11e6-8c7b-118806155c09.jpg)

**Comment by bastelfreak** [comment]
I'm going to close this PR because we're deprecating the module.
