### ISSUE TITLE
RFE: IP address

### ISSUE THREAD

**Issue by roidelapluie** [voxpupuli/puppet-tea#2]
type ipv4address
type ipv6address
type ipaddress = Variant[ipv4address,ipv6address]

**Comment by igalic** [comment]
i imagine we can very easily implement ipv4address with a Pattern.
I have _no_ idea how to implement IPv6 addresses though…

**Comment by roidelapluie** [comment]
A Freaking Regex :-)

**Comment by danzilio** [comment]
We may need to call in an expert...

**Comment by roidelapluie** [comment]
https://gist.github.com/cpetschnig/294476

**Comment by danzilio** [comment]
I believe that regex is banned under the Geneva Conventions as cruel and unusual punishment

**Comment by wyardley** [comment]
There's also
https://github.com/thrnio/puppet-ip/ and
https://github.com/puppetlabs/puppetlabs-stdlib/blob/master/types/compat/ipv4.pp

**Comment by ekohl** [comment]
Stdlib has IP types now.
