### ISSUE TITLE
Update project description

### ISSUE THREAD

**Issue by rnelson0** [voxpupuli/puppet-tea#52]
The current project description `Puppet 4.6 Types: Abstracted & Extracted` seems a bit stale, since we recently required at least Puppet 5.5. The overview and limitations sections of the readme also reference version `4.4+`. I believe this is not in any way tied to 4.x and if true, these references should be cleaned up.

**Comment by rnelson0** [comment]
Alternatively, since the actual types were last updated years ago, the module really is designed for 4.x and should be reverted to such a state and frozen, then removed from modulesync.

**Comment by ekohl** [comment]
Various types are actually in stdlib as well. The only 2 that aren't are https://github.com/voxpupuli/puppet-tea/blob/master/types/awsregion.pp and https://github.com/voxpupuli/puppet-tea/blob/master/types/syslogpriority.pp. :+1: to archiving.

**Comment by alexjfisher** [comment]
stdlib already has a syslogfacility.  We should probably create a PR for syslogpriority and then archive this module.

**Comment by alexjfisher** [comment]
We also have https://github.com/voxpupuli/puppet-rsyslog/blob/master/types/syslog/severity.pp

**Comment by bastelfreak** [comment]
I'm going to close this PR because we're deprecating the module.
